//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtHelp.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtHelp.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string About_closeButton {
            get {
                return ResourceManager.GetString("About_closeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string About_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("About_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco &quot;Cav&quot; Macciò.
        /// </summary>
        internal static string About_createdByLabel {
            get {
                return ResourceManager.GetString("About_createdByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco Macciò.
        /// </summary>
        internal static string About_createdByLabel_FE {
            get {
                return ResourceManager.GetString("About_createdByLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        internal static string About_createdByLabel1 {
            get {
                return ResourceManager.GetString("About_createdByLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp (2009-2011) is licensed under the following Creative Commons Attribution 3.0 License.
        ///creativecommons.org/licenses/by-nc-nd/3.0
        ///
        ///This application requires Microsoft .NET Framework 4 and it is entirely Windows registry-free.
        ///
        ///Main iconset made by Delacro.
        ///delacro.deviantart.com
        ///
        ///Other icons made by Mark James and VistaIcons.
        ///- famfamfam.com
        ///- vistaicons.com
        ///
        ///External component referenced: Log4Net.
        ///- logging.apache.org/log4net
        ///
        ///DtHelp does not collect any info about usage and users. Info [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About_descriptionTextBox {
            get {
                return ResourceManager.GetString("About_descriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write an e-mail to DtHelp&apos;s author.
        /// </summary>
        internal static string About_emailPictureBoxToolTip {
            get {
                return ResourceManager.GetString("About_emailPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read RSS feed of diariotraduttore.com.
        /// </summary>
        internal static string About_rssPictureBoxToolTip {
            get {
                return ResourceManager.GetString("About_rssPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string About_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("About_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp.
        /// </summary>
        internal static string About_titleLabel {
            get {
                return ResourceManager.GetString("About_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp - Family Edition.
        /// </summary>
        internal static string About_titleLabel_FE {
            get {
                return ResourceManager.GetString("About_titleLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string About_versionLabel1 {
            get {
                return ResourceManager.GetString("About_versionLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diariotraduttore.com.
        /// </summary>
        internal static string About_websiteLabel {
            get {
                return ResourceManager.GetString("About_websiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2009.
        /// </summary>
        internal static string About_websiteLabel_FE {
            get {
                return ResourceManager.GetString("About_websiteLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string About_websiteLabel1 {
            get {
                return ResourceManager.GetString("About_websiteLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        internal static string About_websiteLabel1_FE {
            get {
                return ResourceManager.GetString("About_websiteLabel1_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit DtHelp&apos;s author homepage.
        /// </summary>
        internal static string About_websitePictureBoxToolTip {
            get {
                return ResourceManager.GetString("About_websitePictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string EmailManager_Area {
            get {
                return ResourceManager.GetString("EmailManager_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report.
        /// </summary>
        internal static string EmailManager_BugReport {
            get {
                return ResourceManager.GetString("EmailManager_BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string EmailManager_Description {
            get {
                return ResourceManager.GetString("EmailManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailManager_Email {
            get {
                return ResourceManager.GetString("EmailManager_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail field is not correct.
        ///Required format: example@email.com.
        /// </summary>
        internal static string EmailManager_EmailInvalid {
            get {
                return ResourceManager.GetString("EmailManager_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string EmailManager_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailManager_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EmailManager_Name {
            get {
                return ResourceManager.GetString("EmailManager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy error message to clipboard.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy error message to clipboard.
        /// </summary>
        internal static string ErrorOR_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorOR_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorOR_okButton {
            get {
                return ResourceManager.GetString("ErrorOR_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report.
        /// </summary>
        internal static string ErrorOR_reportBugButton {
            get {
                return ResourceManager.GetString("ErrorOR_reportBugButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorOR_Title {
            get {
                return ResourceManager.GetString("ErrorOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Form1_aboutToolStripButton {
            get {
                return ResourceManager.GetString("Form1_aboutToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Form1_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Form1_browserStatusToolStripStatusLabel {
            get {
                return ResourceManager.GetString("Form1_browserStatusToolStripStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Form1_clearToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_clearToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form1_closeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_closeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string Form1_collapseAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_collapseAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Selected Node.
        /// </summary>
        internal static string Form1_collapseSelectedNodeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_collapseSelectedNodeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Form1_connectionStatus_Connected {
            get {
                return ResourceManager.GetString("Form1_connectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Form1_connectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("Form1_connectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem2 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem3 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diario di un traduttore.
        /// </summary>
        internal static string Form1_diarioDiUnTraduttoreToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_diarioDiUnTraduttoreToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Form1_editToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_editToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Form1_englishToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_englishToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Form1_exitToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_exitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string Form1_expandAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_expandAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Selected Node.
        /// </summary>
        internal static string Form1_expandSelectedNodeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_expandSelectedNodeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Form1_fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Form1_goBackToolStripButton {
            get {
                return ResourceManager.GetString("Form1_goBackToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Form1_goBackToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_goBackToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Form1_goBackToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_goBackToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foward.
        /// </summary>
        internal static string Form1_goForwardToolStripButton {
            get {
                return ResourceManager.GetString("Form1_goForwardToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foward.
        /// </summary>
        internal static string Form1_goForwardToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_goForwardToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foward.
        /// </summary>
        internal static string Form1_goForwardToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_goForwardToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Form1_helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Form1_historyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_historyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Form1_homeToolStripButton {
            get {
                return ResourceManager.GetString("Form1_homeToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Form1_homeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_homeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string Form1_italianoToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_italianoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Form1_languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        internal static string Form1_licenseAgreementToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_licenseAgreementToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Form1_office2003ToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_office2003ToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string Form1_openGuideToolStripButton {
            get {
                return ResourceManager.GetString("Form1_openGuideToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string Form1_openGuideToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_openGuideToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup....
        /// </summary>
        internal static string Form1_pageSetupToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_pageSetupToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string Form1_printPreviewToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_printPreviewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        internal static string Form1_printToolStripButton {
            get {
                return ResourceManager.GetString("Form1_printToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        internal static string Form1_printToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_printToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Form1_propertiesToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_propertiesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Form1_refreshToolStripButton {
            get {
                return ResourceManager.GetString("Form1_refreshToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Form1_refreshToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_refreshToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug....
        /// </summary>
        internal static string Form1_reportABugToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_reportABugToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string Form1_saveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_saveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Search Panel.
        /// </summary>
        internal static string Form1_searchToolStripButton {
            get {
                return ResourceManager.GetString("Form1_searchToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Panel.
        /// </summary>
        internal static string Form1_searchToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_searchToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem2 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem3 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Form1_styleToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_styleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string Form1_urlToolStripLabel {
            get {
                return ResourceManager.GetString("Form1_urlToolStripLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Form1_viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_viewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Windows.
        /// </summary>
        internal static string Form1_windowsXPToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_windowsXPToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Form1_windowToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_windowToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide node not found!.
        /// </summary>
        internal static string GuideManager_ErrorGetting {
            get {
                return ResourceManager.GetString("GuideManager_ErrorGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during guide reading..
        /// </summary>
        internal static string GuideManager_ErrorReading {
            get {
                return ResourceManager.GetString("GuideManager_ErrorReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum one input string parameter is allowed..
        /// </summary>
        internal static string Program_InputError {
            get {
                return ResourceManager.GetString("Program_InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///File
        ///Edit
        ///History
        ///Options
        ///View
        ///Guide Index
        ///Other.
        /// </summary>
        internal static string ReportBug_areaComboBoxItems {
            get {
                return ResourceManager.GetString("ReportBug_areaComboBoxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area: *.
        /// </summary>
        internal static string ReportBug_areaLabel {
            get {
                return ResourceManager.GetString("ReportBug_areaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ReportBug_cancelButton {
            get {
                return ResourceManager.GetString("ReportBug_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ReportBug_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ReportBug_cutToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_cutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ReportBug_deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        internal static string ReportBug_descriptionLabel {
            get {
                return ResourceManager.GetString("ReportBug_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail: *.
        /// </summary>
        internal static string ReportBug_emailLabel {
            get {
                return ResourceManager.GetString("ReportBug_emailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message (if present):.
        /// </summary>
        internal static string ReportBug_errorMessageLabel {
            get {
                return ResourceManager.GetString("ReportBug_errorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send via e-mail a bug report to the DtHelp author..
        /// </summary>
        internal static string ReportBug_helpLabel {
            get {
                return ResourceManager.GetString("ReportBug_helpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: *.
        /// </summary>
        internal static string ReportBug_nameLabel {
            get {
                return ResourceManager.GetString("ReportBug_nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ReportBug_pasteToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_pasteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required fields.
        /// </summary>
        internal static string ReportBug_requiredFieldsLabel {
            get {
                return ResourceManager.GetString("ReportBug_requiredFieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ReportBug_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ReportBug_sendButton {
            get {
                return ResourceManager.GetString("ReportBug_sendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a copy.
        /// </summary>
        internal static string ReportBug_sendMeACopyCheckBox {
            get {
                return ResourceManager.GetString("ReportBug_sendMeACopyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Report.
        /// </summary>
        internal static string ReportBug_Title {
            get {
                return ResourceManager.GetString("ReportBug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string ReportBug_undoToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_undoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution interrupted!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal exception occured:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program execution interrupted!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
