//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtHelp.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtHelp.Languages.it", typeof(it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        internal static string About_closeButton {
            get {
                return ResourceManager.GetString("About_closeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string About_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("About_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco &quot;Cav&quot; Macciò.
        /// </summary>
        internal static string About_createdByLabel {
            get {
                return ResourceManager.GetString("About_createdByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco Macciò.
        /// </summary>
        internal static string About_createdByLabel_FE {
            get {
                return ResourceManager.GetString("About_createdByLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scritto da:.
        /// </summary>
        internal static string About_createdByLabel1 {
            get {
                return ResourceManager.GetString("About_createdByLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp (2009-2011) è distribuito sotto licenza Creative Commons Attribution 3.0.
        ///creativecommons.org/licenses/by-nc-nd/3.0
        ///
        ///Questa applicazione richiede Microsoft .NET Framework 4 e non fa uso del registro di Windows.
        ///
        ///Set principale di icone creato da Delacro.
        ///delacro.deviantart.com
        ///
        ///Icone secondarie create da Mark James e VistaIcons.
        ///- famfamfam.com
        ///- vistaicons.com
        ///
        ///Componente esterno referenziato: Log4Net.
        ///- logging.apache.org/log4net
        ///
        ///DtHelp non raccoglie alcuna informazione riguardante  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About_descriptionTextBox {
            get {
                return ResourceManager.GetString("About_descriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrivi una e-mail all&apos;autore di DtHelp.
        /// </summary>
        internal static string About_emailPictureBoxToolTip {
            get {
                return ResourceManager.GetString("About_emailPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggi il feed RSS di diariotraduttore.com.
        /// </summary>
        internal static string About_rssPictureBoxToolTip {
            get {
                return ResourceManager.GetString("About_rssPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string About_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("About_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp.
        /// </summary>
        internal static string About_titleLabel {
            get {
                return ResourceManager.GetString("About_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp - Family Edition.
        /// </summary>
        internal static string About_titleLabel_FE {
            get {
                return ResourceManager.GetString("About_titleLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione:.
        /// </summary>
        internal static string About_versionLabel1 {
            get {
                return ResourceManager.GetString("About_versionLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diariotraduttore.com.
        /// </summary>
        internal static string About_websiteLabel {
            get {
                return ResourceManager.GetString("About_websiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2009.
        /// </summary>
        internal static string About_websiteLabel_FE {
            get {
                return ResourceManager.GetString("About_websiteLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sito web:.
        /// </summary>
        internal static string About_websiteLabel1 {
            get {
                return ResourceManager.GetString("About_websiteLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        internal static string About_websiteLabel1_FE {
            get {
                return ResourceManager.GetString("About_websiteLabel1_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visita la home page dell&apos;autore di DtHelp.
        /// </summary>
        internal static string About_websitePictureBoxToolTip {
            get {
                return ResourceManager.GetString("About_websitePictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string EmailManager_Area {
            get {
                return ResourceManager.GetString("EmailManager_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnalazione errore.
        /// </summary>
        internal static string EmailManager_BugReport {
            get {
                return ResourceManager.GetString("EmailManager_BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        internal static string EmailManager_Description {
            get {
                return ResourceManager.GetString("EmailManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailManager_Email {
            get {
                return ResourceManager.GetString("EmailManager_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il campo e-mail non è corretto.
        ///Formato richiesto: esempio@email.it.
        /// </summary>
        internal static string EmailManager_EmailInvalid {
            get {
                return ResourceManager.GetString("EmailManager_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaggio di errore.
        /// </summary>
        internal static string EmailManager_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailManager_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string EmailManager_Name {
            get {
                return ResourceManager.GetString("EmailManager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia il messaggio di errore negli appunti.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia il messaggio di errore negli appunti.
        /// </summary>
        internal static string ErrorOR_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorOR_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorOR_okButton {
            get {
                return ResourceManager.GetString("ErrorOR_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnala.
        /// </summary>
        internal static string ErrorOR_reportBugButton {
            get {
                return ResourceManager.GetString("ErrorOR_reportBugButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorOR_Title {
            get {
                return ResourceManager.GetString("ErrorOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni.
        /// </summary>
        internal static string Form1_aboutToolStripButton {
            get {
                return ResourceManager.GetString("Form1_aboutToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni.
        /// </summary>
        internal static string Form1_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto.
        /// </summary>
        internal static string Form1_browserStatusToolStripStatusLabel {
            get {
                return ResourceManager.GetString("Form1_browserStatusToolStripStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svuota.
        /// </summary>
        internal static string Form1_clearToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_clearToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        internal static string Form1_closeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_closeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi tutto.
        /// </summary>
        internal static string Form1_collapseAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_collapseAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi nodo selezionato.
        /// </summary>
        internal static string Form1_collapseSelectedNodeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_collapseSelectedNodeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connesso.
        /// </summary>
        internal static string Form1_connectionStatus_Connected {
            get {
                return ResourceManager.GetString("Form1_connectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnesso.
        /// </summary>
        internal static string Form1_connectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("Form1_connectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem2 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem3 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglia.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglia.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diario di un traduttore.
        /// </summary>
        internal static string Form1_diarioDiUnTraduttoreToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_diarioDiUnTraduttoreToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string Form1_editToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_editToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Form1_englishToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_englishToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        internal static string Form1_exitToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_exitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espandi tutto.
        /// </summary>
        internal static string Form1_expandAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_expandAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espandi nodo selezionato.
        /// </summary>
        internal static string Form1_expandSelectedNodeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_expandSelectedNodeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Form1_fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        internal static string Form1_goBackToolStripButton {
            get {
                return ResourceManager.GetString("Form1_goBackToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        internal static string Form1_goBackToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_goBackToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        internal static string Form1_goBackToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_goBackToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanti.
        /// </summary>
        internal static string Form1_goForwardToolStripButton {
            get {
                return ResourceManager.GetString("Form1_goForwardToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanti.
        /// </summary>
        internal static string Form1_goForwardToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_goForwardToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanti.
        /// </summary>
        internal static string Form1_goForwardToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_goForwardToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Form1_helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronologia.
        /// </summary>
        internal static string Form1_historyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_historyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina iniziale.
        /// </summary>
        internal static string Form1_homeToolStripButton {
            get {
                return ResourceManager.GetString("Form1_homeToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina iniziale.
        /// </summary>
        internal static string Form1_homeToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_homeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string Form1_italianoToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_italianoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string Form1_languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenza d&apos;uso.
        /// </summary>
        internal static string Form1_licenseAgreementToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_licenseAgreementToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Form1_office2003ToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_office2003ToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri....
        /// </summary>
        internal static string Form1_openGuideToolStripButton {
            get {
                return ResourceManager.GetString("Form1_openGuideToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri....
        /// </summary>
        internal static string Form1_openGuideToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_openGuideToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni pagina....
        /// </summary>
        internal static string Form1_pageSetupToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_pageSetupToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incolla.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incolla.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteprima stampa.
        /// </summary>
        internal static string Form1_printPreviewToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_printPreviewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa....
        /// </summary>
        internal static string Form1_printToolStripButton {
            get {
                return ResourceManager.GetString("Form1_printToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa....
        /// </summary>
        internal static string Form1_printToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_printToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietà.
        /// </summary>
        internal static string Form1_propertiesToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_propertiesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricarica.
        /// </summary>
        internal static string Form1_refreshToolStripButton {
            get {
                return ResourceManager.GetString("Form1_refreshToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricarica.
        /// </summary>
        internal static string Form1_refreshToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_refreshToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnala errore....
        /// </summary>
        internal static string Form1_reportABugToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_reportABugToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva come....
        /// </summary>
        internal static string Form1_saveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_saveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra pannello di ricerca.
        /// </summary>
        internal static string Form1_searchToolStripButton {
            get {
                return ResourceManager.GetString("Form1_searchToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pannello di ricerca.
        /// </summary>
        internal static string Form1_searchToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_searchToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem2 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem3 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspetto.
        /// </summary>
        internal static string Form1_styleToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_styleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtHelp.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string Form1_urlToolStripLabel {
            get {
                return ResourceManager.GetString("Form1_urlToolStripLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza.
        /// </summary>
        internal static string Form1_viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_viewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows classico.
        /// </summary>
        internal static string Form1_windowsXPToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_windowsXPToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finestra.
        /// </summary>
        internal static string Form1_windowToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_windowToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo della guida non trovato!.
        /// </summary>
        internal static string GuideManager_ErrorGetting {
            get {
                return ResourceManager.GetString("GuideManager_ErrorGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore in apertura della guida..
        /// </summary>
        internal static string GuideManager_ErrorReading {
            get {
                return ResourceManager.GetString("GuideManager_ErrorReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di parametri in ingresso errato. Massimo un parametro consentito..
        /// </summary>
        internal static string Program_InputError {
            get {
                return ResourceManager.GetString("Program_InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///File
        ///Modifica
        ///Cronologia
        ///Opzioni
        ///Aspetto
        ///Indice guida
        ///Altro.
        /// </summary>
        internal static string ReportBug_areaComboBoxItems {
            get {
                return ResourceManager.GetString("ReportBug_areaComboBoxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area: *.
        /// </summary>
        internal static string ReportBug_areaLabel {
            get {
                return ResourceManager.GetString("ReportBug_areaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string ReportBug_cancelButton {
            get {
                return ResourceManager.GetString("ReportBug_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string ReportBug_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglia.
        /// </summary>
        internal static string ReportBug_cutToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_cutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string ReportBug_deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione: *.
        /// </summary>
        internal static string ReportBug_descriptionLabel {
            get {
                return ResourceManager.GetString("ReportBug_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail: *.
        /// </summary>
        internal static string ReportBug_emailLabel {
            get {
                return ResourceManager.GetString("ReportBug_emailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaggio d&apos;errore (se presente):.
        /// </summary>
        internal static string ReportBug_errorMessageLabel {
            get {
                return ResourceManager.GetString("ReportBug_errorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia via e-mail un report di errore all&apos;autore di DtHelp..
        /// </summary>
        internal static string ReportBug_helpLabel {
            get {
                return ResourceManager.GetString("ReportBug_helpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome: *.
        /// </summary>
        internal static string ReportBug_nameLabel {
            get {
                return ResourceManager.GetString("ReportBug_nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incolla.
        /// </summary>
        internal static string ReportBug_pasteToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_pasteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campi obbligatori.
        /// </summary>
        internal static string ReportBug_requiredFieldsLabel {
            get {
                return ResourceManager.GetString("ReportBug_requiredFieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string ReportBug_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia.
        /// </summary>
        internal static string ReportBug_sendButton {
            get {
                return ResourceManager.GetString("ReportBug_sendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inviami una copia.
        /// </summary>
        internal static string ReportBug_sendMeACopyCheckBox {
            get {
                return ResourceManager.GetString("ReportBug_sendMeACopyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnala errore.
        /// </summary>
        internal static string ReportBug_Title {
            get {
                return ResourceManager.GetString("ReportBug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string ReportBug_undoToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportBug_undoToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;esecuzione dell&apos;operazione in corso è stata interrotta!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;esecuzione del programma è stata interrotta!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
