//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUninstaller.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUninstaller.Languages.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar mensaje de error al portapapeles.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Form1_CloseButton {
            get {
                return ResourceManager.GetString("Form1_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller es una aplicación que haga más fácil la desinstalación de DtPad y cada uno de sus componentes.
        ///
        ///Si te gusta hacerlo de forma manual (y no ha activado la integración &quot;Abrir con&quot; dentro de las opciones de diálogo de DtPad) simplemente borre la carpeta del programa.
        ///
        ///De lo contrario, haga clic sobre &quot;Desinstalar&quot; para continuar.
        ///
        ///Si lo desea, haga clic en el enlace de abajo para enviar un mensaje sobre cómo estaba usando DtPad y por qué decidió que desinstalarlo..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic aquí para enviar un e-mail al autor.
        /// </summary>
        internal static string Form1_linkLabel {
            get {
                return ResourceManager.GetString("Form1_linkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todo.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea continuar con la desinstalación de DtPad?
        ///Todos los archivos de configuración se borrarán..
        /// </summary>
        internal static string Form1_SureUninstall {
            get {
                return ResourceManager.GetString("Form1_SureUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar.
        /// </summary>
        internal static string Form1_uninstallButton {
            get {
                return ResourceManager.GetString("Form1_uninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre cualquier instancia de DtHelp antes de iniciar el proceso de desinstalación..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre cualquier instancia de DtPad antes de iniciar el proceso de desinstalación..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una instancia de Dtpad Uninstaller abierta..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre cualquier instancia de DtPad Updater antes de iniciar el proceso de desinstalación..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string QuestionYN_noButton {
            get {
                return ResourceManager.GetString("QuestionYN_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        internal static string QuestionYN_Title {
            get {
                return ResourceManager.GetString("QuestionYN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string QuestionYN_yesButton {
            get {
                return ResourceManager.GetString("QuestionYN_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando acceso directo del escritorio....
        /// </summary>
        internal static string UninstallManager_DeleteDesktop {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eliminado.
        /// </summary>
        internal static string UninstallManager_DeletedFile {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eliminado.
        /// </summary>
        internal static string UninstallManager_DeletedFolder {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eliminado.
        /// </summary>
        internal static string UninstallManager_DeletedKey {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando archivos....
        /// </summary>
        internal static string UninstallManager_DeleteFiles {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando accesos directos del menú Inicio....
        /// </summary>
        internal static string UninstallManager_DeleteLinks {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando asociación &quot;Abrir con&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteOpenWith {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando asociación  &quot;Enviar a&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteSendTo {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error durante el proceso de desinstalación. En el caso de repetición de esto errore, se recomienda eliminar manualmente los archivos contenidos en la carpeta de instalación de DtPad.
        ///Error detalle:.
        /// </summary>
        internal static string UninstallManager_Error {
            get {
                return ResourceManager.GetString("UninstallManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string UninstallManager_File {
            get {
                return ResourceManager.GetString("UninstallManager_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta.
        /// </summary>
        internal static string UninstallManager_Folder {
            get {
                return ResourceManager.GetString("UninstallManager_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        internal static string UninstallManager_Key {
            get {
                return ResourceManager.GetString("UninstallManager_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir con DtPad.
        /// </summary>
        internal static string UninstallManager_ShellString {
            get {
                return ResourceManager.GetString("UninstallManager_ShellString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando desinstalación de DtPad....
        /// </summary>
        internal static string UninstallManager_Start {
            get {
                return ResourceManager.GetString("UninstallManager_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalación completada con éxito!.
        /// </summary>
        internal static string UninstallManager_Success {
            get {
                return ResourceManager.GetString("UninstallManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
    }
}
