//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUninstaller.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUninstaller.Languages.it", typeof(it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia il messaggio di errore negli appunti.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        internal static string Form1_CloseButton {
            get {
                return ResourceManager.GetString("Form1_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller è un&apos;applicazione che rende più facile la disinstallazione di DtPad e dei suoi componenti.
        ///
        ///Se si preferisce procedere a mano (e non si è abilitata l&apos;integrazione &quot;Apri con&quot; nella finestra delle opzioni ), si può semplicemente cancellare la cartella di DtPad.
        ///
        ///Altrimenti cliccare su &quot;Disinstalla&quot; per procedere.
        ///
        ///Se lo si desidera, cliccare sul link sottostante per inviare un messaggio circa l&apos;utilizzo di DtPad e sul perché si è deciso di disinstallarlo..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca qui per inviare una e-mail all&apos;autore.
        /// </summary>
        internal static string Form1_linkLabel {
            get {
                return ResourceManager.GetString("Form1_linkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler procedere con la disinstallazione di DtPad?
        ///Tutti i file di configurazione andranno cancellati..
        /// </summary>
        internal static string Form1_SureUninstall {
            get {
                return ResourceManager.GetString("Form1_SureUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinstalla.
        /// </summary>
        internal static string Form1_uninstallButton {
            get {
                return ResourceManager.GetString("Form1_uninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi ogni finestra di DtHelp prima di avviare il processo di disinstallazione..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi ogni finestra di DtPad prima di avviare il processo di disinstallazione..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esiste già una finestra aperta di DtPad Uninstaller..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi ogni finestra di DtPad Updater prima di avviare il processo di disinstallazione..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string QuestionYN_noButton {
            get {
                return ResourceManager.GetString("QuestionYN_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domanda.
        /// </summary>
        internal static string QuestionYN_Title {
            get {
                return ResourceManager.GetString("QuestionYN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sì.
        /// </summary>
        internal static string QuestionYN_yesButton {
            get {
                return ResourceManager.GetString("QuestionYN_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione collegamento sul desktop....
        /// </summary>
        internal static string UninstallManager_DeleteDesktop {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancellato.
        /// </summary>
        internal static string UninstallManager_DeletedFile {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancellata.
        /// </summary>
        internal static string UninstallManager_DeletedFolder {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancellata.
        /// </summary>
        internal static string UninstallManager_DeletedKey {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione file....
        /// </summary>
        internal static string UninstallManager_DeleteFiles {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione collegamenti nel menu Start....
        /// </summary>
        internal static string UninstallManager_DeleteLinks {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione associazione &quot;Apri con&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteOpenWith {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione associazione nella cartella &quot;Invia a&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteSendTo {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante la fase di disinstallazione. In caso di ripetizione dell&apos;errore si consiglia di cancellare a mano i file contenuti nella cartella di installazione di DtPad.
        ///Dettaglio errore:.
        /// </summary>
        internal static string UninstallManager_Error {
            get {
                return ResourceManager.GetString("UninstallManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string UninstallManager_File {
            get {
                return ResourceManager.GetString("UninstallManager_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartella.
        /// </summary>
        internal static string UninstallManager_Folder {
            get {
                return ResourceManager.GetString("UninstallManager_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiave.
        /// </summary>
        internal static string UninstallManager_Key {
            get {
                return ResourceManager.GetString("UninstallManager_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvio procedura di disinstallazione di DtPad....
        /// </summary>
        internal static string UninstallManager_Start {
            get {
                return ResourceManager.GetString("UninstallManager_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinstallazione completata con successo!.
        /// </summary>
        internal static string UninstallManager_Success {
            get {
                return ResourceManager.GetString("UninstallManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
    }
}
