//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUninstaller.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUninstaller.Languages.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать сообщение об ошибке в буфер.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Form1_CloseButton {
            get {
                return ResourceManager.GetString("Form1_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller - это программа, которое облегчает удаление приложения DtPad и каждого из его компонентов.
        ///
        ///Если вы хотите удалить DtPad вручную (и не включили интеграцию с меню Проводника &quot;Открыть с помощью&quot; в настройках), просто удалите папку приложения.
        ///
        ///В противном случае нажмите кнопку &quot;Удалить&quot;, и приложение будет удалено автоматически.
        ///
        ///При желании щелкните приведенную ниже ссылку и напишите автору, как вам работалось с DtPad и почему вы решили его удалить..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щелкните здесь, чтобы написать автору по электронной почте.
        /// </summary>
        internal static string Form1_linkLabel {
            get {
                return ResourceManager.GetString("Form1_linkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить все.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить DtPad?
        ///При этом будут удалены все конфигурационные файлы..
        /// </summary>
        internal static string Form1_SureUninstall {
            get {
                return ResourceManager.GetString("Form1_SureUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Form1_uninstallButton {
            get {
                return ResourceManager.GetString("Form1_uninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте все работающие экземпляры DtHelp, прежде чем приступать к удалению..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте все работающие экземпляры DtPad, прежде чем приступать к удалению..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Uninstaller уже открыт..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте все работающие экземпляры DtPad Updater, прежде чем приступать к удалению..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string QuestionYN_noButton {
            get {
                return ResourceManager.GetString("QuestionYN_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        internal static string QuestionYN_Title {
            get {
                return ResourceManager.GetString("QuestionYN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string QuestionYN_yesButton {
            get {
                return ResourceManager.GetString("QuestionYN_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление ярлыка с рабочего стола....
        /// </summary>
        internal static string UninstallManager_DeleteDesktop {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удален.
        /// </summary>
        internal static string UninstallManager_DeletedFile {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удален.
        /// </summary>
        internal static string UninstallManager_DeletedFolder {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удален.
        /// </summary>
        internal static string UninstallManager_DeletedKey {
            get {
                return ResourceManager.GetString("UninstallManager_DeletedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление файлов....
        /// </summary>
        internal static string UninstallManager_DeleteFiles {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление ярлыков из меню &quot;Пуск&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteLinks {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление сопоставления для меню &quot;Открыть с помощью&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteOpenWith {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление сопоставления файлов для меню &quot;Открыть с помощью&quot;....
        /// </summary>
        internal static string UninstallManager_DeleteSendTo {
            get {
                return ResourceManager.GetString("UninstallManager_DeleteSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При удалении произошла ошибка. Если она будет повторяться, рекомендуется вручную удалить файлы из папки, где установлена программа DtPad.
        ///Сведения об ошибке:.
        /// </summary>
        internal static string UninstallManager_Error {
            get {
                return ResourceManager.GetString("UninstallManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string UninstallManager_File {
            get {
                return ResourceManager.GetString("UninstallManager_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        internal static string UninstallManager_Folder {
            get {
                return ResourceManager.GetString("UninstallManager_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        internal static string UninstallManager_Key {
            get {
                return ResourceManager.GetString("UninstallManager_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск процесса удаления DtPad....
        /// </summary>
        internal static string UninstallManager_Start {
            get {
                return ResourceManager.GetString("UninstallManager_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение удалено..
        /// </summary>
        internal static string UninstallManager_Success {
            get {
                return ResourceManager.GetString("UninstallManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникло исключение:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникло неустранимое исключение:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
    }
}
