//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadSetup.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadSetup.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy error message to clipboard.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available space:.
        /// </summary>
        internal static string Form1_availableSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_availableSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Form1_backButton {
            get {
                return ResourceManager.GetString("Form1_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Form1_browseButton {
            get {
                return ResourceManager.GetString("Form1_browseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where to install DtPad:.
        /// </summary>
        internal static string Form1_BrowseDescription {
            get {
                return ResourceManager.GetString("Form1_BrowseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Form1_cancelButtonExit {
            get {
                return ResourceManager.GetString("Form1_cancelButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your destination path:.
        /// </summary>
        internal static string Form1_destinationPathLabel {
            get {
                return ResourceManager.GetString("Form1_destinationPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        internal static string Form1_domainLabel {
            get {
                return ResourceManager.GetString("Form1_domainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Form1_dotNetRadioButton {
            get {
                return ResourceManager.GetString("Form1_dotNetRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable proxy settings.
        /// </summary>
        internal static string Form1_enableProxySettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_enableProxySettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Form1_EndPhase {
            get {
                return ResourceManager.GetString("Form1_EndPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where to place DtPad:.
        /// </summary>
        internal static string Form1_folderBrowserDialog {
            get {
                return ResourceManager.GetString("Form1_folderBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information: for the moment DtPad supports english,
        ///italian, french and spanish languages. Maybe next
        ///versions will support even other cultures. If you are
        ///interested in giving help for other localizations, contact
        ///me using the form contained on the following page..
        /// </summary>
        internal static string Form1_infoLabel {
            get {
                return ResourceManager.GetString("Form1_infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Form1_installGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_installGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Form1_InstallPhase {
            get {
                return ResourceManager.GetString("Form1_InstallPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Form1_internetGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_internetGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Form1_InternetPhase {
            get {
                return ResourceManager.GetString("Form1_InternetPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad.
        /// </summary>
        internal static string Form1_introHeaderLabel {
            get {
                return ResourceManager.GetString("Form1_introHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DtPad setup!
        ///
        ///DtPad is a text editor, based on .NET Framework 4 (REQUIRED, if you do not own it, download it from Microsoft website) and licensed under Apache License, Version 2.0 (apache.org/licenses/LICENSE-2.0).
        ///
        ///Click on &quot;Next&quot; button to proceed..
        /// </summary>
        internal static string Form1_introLabel {
            get {
                return ResourceManager.GetString("Form1_introLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        internal static string Form1_IntroPhase {
            get {
                return ResourceManager.GetString("Form1_IntroPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information: DtPad use Internet Explorer settings to
        ///connect on Internet.
        ///If your PC is behind a proxy server which requires an
        ///authentication, insert here your username and
        ///password..
        /// </summary>
        internal static string Form1_label1 {
            get {
                return ResourceManager.GetString("Form1_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Form1_languageGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_languageGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        internal static string Form1_languageLabel {
            get {
                return ResourceManager.GetString("Form1_languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Form1_LanguagePhase {
            get {
                return ResourceManager.GetString("Form1_LanguagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diariotraduttore.com/contatti.
        /// </summary>
        internal static string Form1_linkContattiLabel {
            get {
                return ResourceManager.GetString("Form1_linkContattiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Form1_lookAndFeelGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_lookAndFeelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look And Feel.
        /// </summary>
        internal static string Form1_LookAndFeelPhase {
            get {
                return ResourceManager.GetString("Form1_LookAndFeelPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on tray icon.
        /// </summary>
        internal static string Form1_minimizeOnTrayIconCheckBox {
            get {
                return ResourceManager.GetString("Form1_minimizeOnTrayIconCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Form1_nextButton {
            get {
                return ResourceManager.GetString("Form1_nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Form1_nextButtonInstall {
            get {
                return ResourceManager.GetString("Form1_nextButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start DtPad.
        /// </summary>
        internal static string Form1_nextButtonStart {
            get {
                return ResourceManager.GetString("Form1_nextButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Form1_passwordLabel {
            get {
                return ResourceManager.GetString("Form1_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required space:.
        /// </summary>
        internal static string Form1_requiredSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_requiredSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create association on &quot;Send To&quot; folder.
        /// </summary>
        internal static string Form1_sendToCheckBox {
            get {
                return ResourceManager.GetString("Form1_sendToCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create link into Windows Explorer context menu.
        /// </summary>
        internal static string Form1_shellCheckBox {
            get {
                return ResourceManager.GetString("Form1_shellCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcuts on Start menu and desktop.
        /// </summary>
        internal static string Form1_shortcutsCheckBox {
            get {
                return ResourceManager.GetString("Form1_shortcutsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip settings (it will be possible to change them
        ///using options window).
        /// </summary>
        internal static string Form1_skipSettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_skipSettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Form1_statusLabel {
            get {
                return ResourceManager.GetString("Form1_statusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on top.
        /// </summary>
        internal static string Form1_stayOnTopCheckBox {
            get {
                return ResourceManager.GetString("Form1_stayOnTopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        internal static string Form1_stepLabel {
            get {
                return ResourceManager.GetString("Form1_stepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Form1_testProxyButton {
            get {
                return ResourceManager.GetString("Form1_testProxyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Setup.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Form1_Unavailable {
            get {
                return ResourceManager.GetString("Form1_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Form1_usernameLabel {
            get {
                return ResourceManager.GetString("Form1_usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Form1_windowGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_windowGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Form1_WindowPhase {
            get {
                return ResourceManager.GetString("Form1_WindowPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Windows.
        /// </summary>
        internal static string Form1_windowsRadioButton {
            get {
                return ResourceManager.GetString("Form1_windowsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &quot;Send To&quot; association....
        /// </summary>
        internal static string InstallManager_CreatingAssociation {
            get {
                return ResourceManager.GetString("InstallManager_CreatingAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new directories....
        /// </summary>
        internal static string InstallManager_CreatingDir {
            get {
                return ResourceManager.GetString("InstallManager_CreatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Start menu shortcuts....
        /// </summary>
        internal static string InstallManager_CreatingShortcut {
            get {
                return ResourceManager.GetString("InstallManager_CreatingShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder already contains DtPad. Are you sure to proceed?
        ///
        ///All configuration files will be maintained, while program will be overwritten..
        /// </summary>
        internal static string InstallManager_DestinationDirWithDtPad {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder already contains files. Are you sure to proceed?
        ///
        ///DtPad files will be added to the folder..
        /// </summary>
        internal static string InstallManager_DestinationDirWithFiles {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Start DtPad&quot; button to open the text editor..
        /// </summary>
        internal static string InstallManager_EndInfo {
            get {
                return ResourceManager.GetString("InstallManager_EndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during setup!.
        /// </summary>
        internal static string InstallManager_Error1 {
            get {
                return ResourceManager.GetString("InstallManager_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files could be remained inside the installation folder..
        /// </summary>
        internal static string InstallManager_Error2 {
            get {
                return ResourceManager.GetString("InstallManager_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string InstallManager_Exception {
            get {
                return ResourceManager.GetString("InstallManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files....
        /// </summary>
        internal static string InstallManager_ExtractingFile {
            get {
                return ResourceManager.GetString("InstallManager_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed successfully!.
        /// </summary>
        internal static string InstallManager_InstallComplete {
            get {
                return ResourceManager.GetString("InstallManager_InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install process interrupted by user..
        /// </summary>
        internal static string InstallManager_InstallInterrupted {
            get {
                return ResourceManager.GetString("InstallManager_InstallInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrating DtPad into Windows Explorer context menu....
        /// </summary>
        internal static string InstallManager_IntegratingShell {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during Windows Explorer context menu integration!.
        /// </summary>
        internal static string InstallManager_IntegratingShellError {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch DtPad.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPad {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch DtPad Uninstaller.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUninstaller {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch DtPad Updater.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUpdater {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read some informations about DtPad.
        /// </summary>
        internal static string InstallManager_LinkReadme {
            get {
                return ResourceManager.GetString("InstallManager_LinkReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string InstallManager_LinkWebsite {
            get {
                return ResourceManager.GetString("InstallManager_LinkWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing installation....
        /// </summary>
        internal static string InstallManager_PreparingInstall {
            get {
                return ResourceManager.GetString("InstallManager_PreparingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with DtPad.
        /// </summary>
        internal static string InstallManager_ShellString {
            get {
                return ResourceManager.GetString("InstallManager_ShellString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string InstallManager_Unavailable {
            get {
                return ResourceManager.GetString("InstallManager_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating settings....
        /// </summary>
        internal static string InstallManager_UpdatingSetting {
            get {
                return ResourceManager.GetString("InstallManager_UpdatingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout!
        ///Test required more then {0} second to be completed..
        /// </summary>
        internal static string OptionManager_ConnectionTimeout {
            get {
                return ResourceManager.GetString("OptionManager_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string WarningYNC_cancelButton {
            get {
                return ResourceManager.GetString("WarningYNC_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string WarningYNC_noButton {
            get {
                return ResourceManager.GetString("WarningYNC_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningYNC_Title {
            get {
                return ResourceManager.GetString("WarningYNC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string WarningYNC_yesButton {
            get {
                return ResourceManager.GetString("WarningYNC_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution interrupted!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal exception occured:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program execution interrupted!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
