//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadSetup.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadSetup.Languages.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar mensaje de error al portapapeles.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio dispon.:.
        /// </summary>
        internal static string Form1_availableSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_availableSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Atrás.
        /// </summary>
        internal static string Form1_backButton {
            get {
                return ResourceManager.GetString("Form1_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar....
        /// </summary>
        internal static string Form1_browseButton {
            get {
                return ResourceManager.GetString("Form1_browseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la carpeta donde desea instalar DtPad:.
        /// </summary>
        internal static string Form1_BrowseDescription {
            get {
                return ResourceManager.GetString("Form1_BrowseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string Form1_cancelButtonExit {
            get {
                return ResourceManager.GetString("Form1_cancelButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortar.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar la carpeta de destino:.
        /// </summary>
        internal static string Form1_destinationPathLabel {
            get {
                return ResourceManager.GetString("Form1_destinationPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominio:.
        /// </summary>
        internal static string Form1_domainLabel {
            get {
                return ResourceManager.GetString("Form1_domainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estándar.
        /// </summary>
        internal static string Form1_dotNetRadioButton {
            get {
                return ResourceManager.GetString("Form1_dotNetRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar configuración del proxy.
        /// </summary>
        internal static string Form1_enableProxySettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_enableProxySettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        internal static string Form1_EndPhase {
            get {
                return ResourceManager.GetString("Form1_EndPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la carpeta donde colocar DtPad:.
        /// </summary>
        internal static string Form1_folderBrowserDialog {
            get {
                return ResourceManager.GetString("Form1_folderBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información: para el momento DtPad soporta los
        ///idiomas inglés, italiano, francés y español. Quizás
        ///próximas versiones apoyará incluso otras culturas.
        ///Si usted está interesado en dar ayuda a otras
        ///idiomas, ponerse en contacto conmigo a través del
        ///formulario que figura en la página siguiente..
        /// </summary>
        internal static string Form1_infoLabel {
            get {
                return ResourceManager.GetString("Form1_infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar.
        /// </summary>
        internal static string Form1_installGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_installGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar.
        /// </summary>
        internal static string Form1_InstallPhase {
            get {
                return ResourceManager.GetString("Form1_InstallPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión.
        /// </summary>
        internal static string Form1_internetGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_internetGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Form1_InternetPhase {
            get {
                return ResourceManager.GetString("Form1_InternetPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad.
        /// </summary>
        internal static string Form1_introHeaderLabel {
            get {
                return ResourceManager.GetString("Form1_introHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a la instalación de DtPad!
        ///
        ///DtPad es un editor de texto, basado en .NET Framework 4 (OBLIGATORIO, si no lo posee, puede descargarlo del sitio web de Microsoft) y licenciado bajo Apache License, Version 2.0 (apache.org/licenses/LICENSE-2.0).
        ///
        ///Haga clic en &quot;Siguiente&quot; para continuar..
        /// </summary>
        internal static string Form1_introLabel {
            get {
                return ResourceManager.GetString("Form1_introLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducción.
        /// </summary>
        internal static string Form1_IntroPhase {
            get {
                return ResourceManager.GetString("Form1_IntroPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información: DtPad utiliza la configuración de
        ///Internet Explorer para conectarse a Internet.
        ///Si su PC está detrás de un servidor proxy que
        ///requiere una autenticación, introduzca aquí su
        ///nombre de usuario y contraseña..
        /// </summary>
        internal static string Form1_label1 {
            get {
                return ResourceManager.GetString("Form1_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Form1_languageGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_languageGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione su idioma:.
        /// </summary>
        internal static string Form1_languageLabel {
            get {
                return ResourceManager.GetString("Form1_languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Form1_LanguagePhase {
            get {
                return ResourceManager.GetString("Form1_LanguagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diariotraduttore.com/contatti.
        /// </summary>
        internal static string Form1_linkContattiLabel {
            get {
                return ResourceManager.GetString("Form1_linkContattiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo.
        /// </summary>
        internal static string Form1_lookAndFeelGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_lookAndFeelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apariencia.
        /// </summary>
        internal static string Form1_LookAndFeelPhase {
            get {
                return ResourceManager.GetString("Form1_LookAndFeelPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizar como icono de la bandeja.
        /// </summary>
        internal static string Form1_minimizeOnTrayIconCheckBox {
            get {
                return ResourceManager.GetString("Form1_minimizeOnTrayIconCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente &gt;.
        /// </summary>
        internal static string Form1_nextButton {
            get {
                return ResourceManager.GetString("Form1_nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar.
        /// </summary>
        internal static string Form1_nextButtonInstall {
            get {
                return ResourceManager.GetString("Form1_nextButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar DtPad.
        /// </summary>
        internal static string Form1_nextButtonStart {
            get {
                return ResourceManager.GetString("Form1_nextButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        internal static string Form1_passwordLabel {
            get {
                return ResourceManager.GetString("Form1_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio neces.:.
        /// </summary>
        internal static string Form1_requiredSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_requiredSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todo.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todo.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear asociación en &quot;Enviar a&quot; carpeta.
        /// </summary>
        internal static string Form1_sendToCheckBox {
            get {
                return ResourceManager.GetString("Form1_sendToCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear vinculo en menú contextual del Explorador.
        /// </summary>
        internal static string Form1_shellCheckBox {
            get {
                return ResourceManager.GetString("Form1_shellCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear accesos directos en menú Inicio y escritorio.
        /// </summary>
        internal static string Form1_shortcutsCheckBox {
            get {
                return ResourceManager.GetString("Form1_shortcutsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltar ajustes (será posible cambiarlos usando la
        ///ventana de opciones).
        /// </summary>
        internal static string Form1_skipSettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_skipSettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        internal static string Form1_statusLabel {
            get {
                return ResourceManager.GetString("Form1_statusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estar al tanto de otras ventanas.
        /// </summary>
        internal static string Form1_stayOnTopCheckBox {
            get {
                return ResourceManager.GetString("Form1_stayOnTopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducción.
        /// </summary>
        internal static string Form1_stepLabel {
            get {
                return ResourceManager.GetString("Form1_stepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobar.
        /// </summary>
        internal static string Form1_testProxyButton {
            get {
                return ResourceManager.GetString("Form1_testProxyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Setup.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No disponible.
        /// </summary>
        internal static string Form1_Unavailable {
            get {
                return ResourceManager.GetString("Form1_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshacer.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        internal static string Form1_usernameLabel {
            get {
                return ResourceManager.GetString("Form1_usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana.
        /// </summary>
        internal static string Form1_windowGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_windowGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana.
        /// </summary>
        internal static string Form1_WindowPhase {
            get {
                return ResourceManager.GetString("Form1_WindowPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana clásico.
        /// </summary>
        internal static string Form1_windowsRadioButton {
            get {
                return ResourceManager.GetString("Form1_windowsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando asociación &quot;Enviar a&quot;....
        /// </summary>
        internal static string InstallManager_CreatingAssociation {
            get {
                return ResourceManager.GetString("InstallManager_CreatingAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando carpetas nuevas....
        /// </summary>
        internal static string InstallManager_CreatingDir {
            get {
                return ResourceManager.GetString("InstallManager_CreatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando accesos directos en el menú Inicio....
        /// </summary>
        internal static string InstallManager_CreatingShortcut {
            get {
                return ResourceManager.GetString("InstallManager_CreatingShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta de destino ya contiene DtPad. ¿Está seguro que desea continuar?
        ///
        ///Todos los archivos de configuración se mantendrá, mientras que el programa se sobrescribirá..
        /// </summary>
        internal static string InstallManager_DestinationDirWithDtPad {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta de destino ya contiene archivos. ¿Está seguro que desea continuar?
        ///
        ///Los archivos de DtPad se añadirá a la carpeta..
        /// </summary>
        internal static string InstallManager_DestinationDirWithFiles {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic en &quot;Iniciar DtPad&quot; para abrir el editor de texto..
        /// </summary>
        internal static string InstallManager_EndInfo {
            get {
                return ResourceManager.GetString("InstallManager_EndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error durante la instalación!.
        /// </summary>
        internal static string InstallManager_Error1 {
            get {
                return ResourceManager.GetString("InstallManager_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tal vez algunos archivos permanecen en el interior de la carpeta de instalación..
        /// </summary>
        internal static string InstallManager_Error2 {
            get {
                return ResourceManager.GetString("InstallManager_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción:.
        /// </summary>
        internal static string InstallManager_Exception {
            get {
                return ResourceManager.GetString("InstallManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrayendo archivos....
        /// </summary>
        internal static string InstallManager_ExtractingFile {
            get {
                return ResourceManager.GetString("InstallManager_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación completada correctamente!.
        /// </summary>
        internal static string InstallManager_InstallComplete {
            get {
                return ResourceManager.GetString("InstallManager_InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalación interrumpida por el usuario..
        /// </summary>
        internal static string InstallManager_InstallInterrupted {
            get {
                return ResourceManager.GetString("InstallManager_InstallInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrando DtPad en el menú contextual del Explorador de Windows....
        /// </summary>
        internal static string InstallManager_IntegratingShell {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la integración en menú contextual del Explorador de Windows!.
        /// </summary>
        internal static string InstallManager_IntegratingShellError {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar DtPad.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPad {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar DtPad Uninstaller.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUninstaller {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar DtPad Updater.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUpdater {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leer algunas informaciones sobre DtPad.
        /// </summary>
        internal static string InstallManager_LinkReadme {
            get {
                return ResourceManager.GetString("InstallManager_LinkReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitio web.
        /// </summary>
        internal static string InstallManager_LinkWebsite {
            get {
                return ResourceManager.GetString("InstallManager_LinkWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando la instalación....
        /// </summary>
        internal static string InstallManager_PreparingInstall {
            get {
                return ResourceManager.GetString("InstallManager_PreparingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir con DtPad.
        /// </summary>
        internal static string InstallManager_ShellString {
            get {
                return ResourceManager.GetString("InstallManager_ShellString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No disponible.
        /// </summary>
        internal static string InstallManager_Unavailable {
            get {
                return ResourceManager.GetString("InstallManager_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando configuración....
        /// </summary>
        internal static string InstallManager_UpdatingSetting {
            get {
                return ResourceManager.GetString("InstallManager_UpdatingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de espera de la conexión!
        ///Prueba requiere más de {0} segundos para completarse..
        /// </summary>
        internal static string OptionManager_ConnectionTimeout {
            get {
                return ResourceManager.GetString("OptionManager_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string WarningYNC_cancelButton {
            get {
                return ResourceManager.GetString("WarningYNC_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string WarningYNC_noButton {
            get {
                return ResourceManager.GetString("WarningYNC_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string WarningYNC_Title {
            get {
                return ResourceManager.GetString("WarningYNC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string WarningYNC_yesButton {
            get {
                return ResourceManager.GetString("WarningYNC_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecución de comandos interrumpida!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecución del programa interrumpido!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
