//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadSetup.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadSetup.Languages.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier le message d&apos;erreur dans le presse-papier.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume dispon.:.
        /// </summary>
        internal static string Form1_availableSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_availableSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Retour.
        /// </summary>
        internal static string Form1_backButton {
            get {
                return ResourceManager.GetString("Form1_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naviguer….
        /// </summary>
        internal static string Form1_browseButton {
            get {
                return ResourceManager.GetString("Form1_browseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le répertoire d&apos;installation de DtPad:.
        /// </summary>
        internal static string Form1_BrowseDescription {
            get {
                return ResourceManager.GetString("Form1_BrowseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortir.
        /// </summary>
        internal static string Form1_cancelButtonExit {
            get {
                return ResourceManager.GetString("Form1_cancelButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez chemin de destination:.
        /// </summary>
        internal static string Form1_destinationPathLabel {
            get {
                return ResourceManager.GetString("Form1_destinationPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        internal static string Form1_domainLabel {
            get {
                return ResourceManager.GetString("Form1_domainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Form1_dotNetRadioButton {
            get {
                return ResourceManager.GetString("Form1_dotNetRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoriser les paramètres du proxy.
        /// </summary>
        internal static string Form1_enableProxySettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_enableProxySettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        internal static string Form1_EndPhase {
            get {
                return ResourceManager.GetString("Form1_EndPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le répertoire où placer DtPad:.
        /// </summary>
        internal static string Form1_folderBrowserDialog {
            get {
                return ResourceManager.GetString("Form1_folderBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information: pour le moment DtPad existe en Anglais,
        ///Italien, Français et Espagnol. Si vous êtes intéressé
        ///pour aider pour d&apos;autres localisations, veuillez me
        ///contacter en utilisant le formulaire de la page suivante..
        /// </summary>
        internal static string Form1_infoLabel {
            get {
                return ResourceManager.GetString("Form1_infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string Form1_installGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_installGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string Form1_InstallPhase {
            get {
                return ResourceManager.GetString("Form1_InstallPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        internal static string Form1_internetGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_internetGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Form1_InternetPhase {
            get {
                return ResourceManager.GetString("Form1_InternetPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad.
        /// </summary>
        internal static string Form1_introHeaderLabel {
            get {
                return ResourceManager.GetString("Form1_introHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans l&apos;installation de DtPad!
        ///
        ///DtPad est un éditeur de texte basé sur le Framework .NET 4 (Si vous ne l&apos;avez pas sur votre ordinateur, téléchargez le depuis le site Microsoft) et sous licence Apache version 2,0 (apache.org/licences/LICENCE-2.0).
        ///
        ///Cliquer sur le bouton &quot;Suivant&quot; pour poursuivre..
        /// </summary>
        internal static string Form1_introLabel {
            get {
                return ResourceManager.GetString("Form1_introLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string Form1_IntroPhase {
            get {
                return ResourceManager.GetString("Form1_IntroPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information: DtPad utilise les paramètres 
        ///d&apos;Internet Explorer pour se connecter à Internet.
        ///Si votre PC est localisé derrière un serveur proxy
        ///nécessitant une authentification, veuillez insérer
        ///ici votre nom d&apos;utilisateur et mot de passe..
        /// </summary>
        internal static string Form1_label1 {
            get {
                return ResourceManager.GetString("Form1_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string Form1_languageGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_languageGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner la langue:.
        /// </summary>
        internal static string Form1_languageLabel {
            get {
                return ResourceManager.GetString("Form1_languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string Form1_LanguagePhase {
            get {
                return ResourceManager.GetString("Form1_LanguagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diariotraduttore.com/contatti.
        /// </summary>
        internal static string Form1_linkContattiLabel {
            get {
                return ResourceManager.GetString("Form1_linkContattiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Form1_lookAndFeelGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_lookAndFeelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparence.
        /// </summary>
        internal static string Form1_LookAndFeelPhase {
            get {
                return ResourceManager.GetString("Form1_LookAndFeelPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réduire avec une icône dans la barre de tâches.
        /// </summary>
        internal static string Form1_minimizeOnTrayIconCheckBox {
            get {
                return ResourceManager.GetString("Form1_minimizeOnTrayIconCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant &gt;.
        /// </summary>
        internal static string Form1_nextButton {
            get {
                return ResourceManager.GetString("Form1_nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string Form1_nextButtonInstall {
            get {
                return ResourceManager.GetString("Form1_nextButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer DtPad.
        /// </summary>
        internal static string Form1_nextButtonStart {
            get {
                return ResourceManager.GetString("Form1_nextButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot passe:.
        /// </summary>
        internal static string Form1_passwordLabel {
            get {
                return ResourceManager.GetString("Form1_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume requis:.
        /// </summary>
        internal static string Form1_requiredSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_requiredSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner tout.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner tout.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer l&apos;association &quot;Envoyer vers&quot;.
        /// </summary>
        internal static string Form1_sendToCheckBox {
            get {
                return ResourceManager.GetString("Form1_sendToCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création lien en menu contextuel de l&apos;Explorateur.
        /// </summary>
        internal static string Form1_shellCheckBox {
            get {
                return ResourceManager.GetString("Form1_shellCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création des raccourcis démarrage et bureau.
        /// </summary>
        internal static string Form1_shortcutsCheckBox {
            get {
                return ResourceManager.GetString("Form1_shortcutsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorer les paramètres (il sera possible de 
        ///les modifier plus tard)..
        /// </summary>
        internal static string Form1_skipSettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_skipSettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut:.
        /// </summary>
        internal static string Form1_statusLabel {
            get {
                return ResourceManager.GetString("Form1_statusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garder au dessus.
        /// </summary>
        internal static string Form1_stayOnTopCheckBox {
            get {
                return ResourceManager.GetString("Form1_stayOnTopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string Form1_stepLabel {
            get {
                return ResourceManager.GetString("Form1_stepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier.
        /// </summary>
        internal static string Form1_testProxyButton {
            get {
                return ResourceManager.GetString("Form1_testProxyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Setup.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indisponible.
        /// </summary>
        internal static string Form1_Unavailable {
            get {
                return ResourceManager.GetString("Form1_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur:.
        /// </summary>
        internal static string Form1_usernameLabel {
            get {
                return ResourceManager.GetString("Form1_usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenêtre.
        /// </summary>
        internal static string Form1_windowGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_windowGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenêtre.
        /// </summary>
        internal static string Form1_WindowPhase {
            get {
                return ResourceManager.GetString("Form1_WindowPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows classique.
        /// </summary>
        internal static string Form1_windowsRadioButton {
            get {
                return ResourceManager.GetString("Form1_windowsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de l&apos;association &quot;Envoyer vers&quot;....
        /// </summary>
        internal static string InstallManager_CreatingAssociation {
            get {
                return ResourceManager.GetString("InstallManager_CreatingAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de nouveaux répertoires....
        /// </summary>
        internal static string InstallManager_CreatingDir {
            get {
                return ResourceManager.GetString("InstallManager_CreatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création des raccourcis du menu de démarrage....
        /// </summary>
        internal static string InstallManager_CreatingShortcut {
            get {
                return ResourceManager.GetString("InstallManager_CreatingShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire de destination contient déjà DtPad. Voulez vous continuer?
        ///
        ///Tous les fichiers de configuration seront conservés, alors que le programme sera ecrasé..
        /// </summary>
        internal static string InstallManager_DestinationDirWithDtPad {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire de destinationcontients des fichiers. Voulez vous continuer?
        ///
        ///Les fichiers de DtPad seront ajoutés au dossier..
        /// </summary>
        internal static string InstallManager_DestinationDirWithFiles {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer sur le bouton &quot;Démarrer DtPad&quot; pour ouvrir l&apos;editeur de texte..
        /// </summary>
        internal static string InstallManager_EndInfo {
            get {
                return ResourceManager.GetString("InstallManager_EndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;installation!.
        /// </summary>
        internal static string InstallManager_Error1 {
            get {
                return ResourceManager.GetString("InstallManager_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certains fichiers peuvent toujours exister dans le répertoire d&apos;installation..
        /// </summary>
        internal static string InstallManager_Error2 {
            get {
                return ResourceManager.GetString("InstallManager_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string InstallManager_Exception {
            get {
                return ResourceManager.GetString("InstallManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction des fichiers en cours….
        /// </summary>
        internal static string InstallManager_ExtractingFile {
            get {
                return ResourceManager.GetString("InstallManager_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;Installation s&apos;est effectuée correctement!.
        /// </summary>
        internal static string InstallManager_InstallComplete {
            get {
                return ResourceManager.GetString("InstallManager_InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;installation a été interompue par l&apos;utilisateur..
        /// </summary>
        internal static string InstallManager_InstallInterrupted {
            get {
                return ResourceManager.GetString("InstallManager_InstallInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intégration de DtPad dans le menu contextuel de l&apos;Explorateur de Windows....
        /// </summary>
        internal static string InstallManager_IntegratingShell {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;intégration dans le menu contextuel de l&apos;Explorateur de Windows!.
        /// </summary>
        internal static string InstallManager_IntegratingShellError {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer DtPad.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPad {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer DtPad Uninstaller.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUninstaller {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer les mises à jour de DtPad.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUpdater {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelques Informations à propos de DtPad.
        /// </summary>
        internal static string InstallManager_LinkReadme {
            get {
                return ResourceManager.GetString("InstallManager_LinkReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site web.
        /// </summary>
        internal static string InstallManager_LinkWebsite {
            get {
                return ResourceManager.GetString("InstallManager_LinkWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préparation de l&apos;installation....
        /// </summary>
        internal static string InstallManager_PreparingInstall {
            get {
                return ResourceManager.GetString("InstallManager_PreparingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir avec DtPad.
        /// </summary>
        internal static string InstallManager_ShellString {
            get {
                return ResourceManager.GetString("InstallManager_ShellString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indisponible.
        /// </summary>
        internal static string InstallManager_Unavailable {
            get {
                return ResourceManager.GetString("InstallManager_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour des paramètres....
        /// </summary>
        internal static string InstallManager_UpdatingSetting {
            get {
                return ResourceManager.GetString("InstallManager_UpdatingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion trop longue à s&apos;établir!
        ///Le test nécessite plus de {0} secondes..
        /// </summary>
        internal static string OptionManager_ConnectionTimeout {
            get {
                return ResourceManager.GetString("OptionManager_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string WarningYNC_cancelButton {
            get {
                return ResourceManager.GetString("WarningYNC_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string WarningYNC_noButton {
            get {
                return ResourceManager.GetString("WarningYNC_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement.
        /// </summary>
        internal static string WarningYNC_Title {
            get {
                return ResourceManager.GetString("WarningYNC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string WarningYNC_yesButton {
            get {
                return ResourceManager.GetString("WarningYNC_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécution de la commande interrompue!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une exception est survenue:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une exception fatale a eu lieu:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;exécution du programme a été interompue!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
