//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadSetup.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadSetup.Languages.it", typeof(it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia il messaggio di errore negli appunti.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazio disponib.:.
        /// </summary>
        internal static string Form1_availableSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_availableSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Indietro.
        /// </summary>
        internal static string Form1_backButton {
            get {
                return ResourceManager.GetString("Form1_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfoglia....
        /// </summary>
        internal static string Form1_browseButton {
            get {
                return ResourceManager.GetString("Form1_browseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la cartella dove installare DtPad:.
        /// </summary>
        internal static string Form1_BrowseDescription {
            get {
                return ResourceManager.GetString("Form1_BrowseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        internal static string Form1_cancelButtonExit {
            get {
                return ResourceManager.GetString("Form1_cancelButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglia.
        /// </summary>
        internal static string Form1_cutToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_cutToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string Form1_deleteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_deleteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la cartella di destinazione:.
        /// </summary>
        internal static string Form1_destinationPathLabel {
            get {
                return ResourceManager.GetString("Form1_destinationPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominio:.
        /// </summary>
        internal static string Form1_domainLabel {
            get {
                return ResourceManager.GetString("Form1_domainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Form1_dotNetRadioButton {
            get {
                return ResourceManager.GetString("Form1_dotNetRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilita impostazioni proxy.
        /// </summary>
        internal static string Form1_enableProxySettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_enableProxySettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        internal static string Form1_EndPhase {
            get {
                return ResourceManager.GetString("Form1_EndPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la cartella dove posizionare DtPad:.
        /// </summary>
        internal static string Form1_folderBrowserDialog {
            get {
                return ResourceManager.GetString("Form1_folderBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazione: per il momento DtPad supporta la lingua inglese, italiana, francese e spagnola. Versioni future potrebbero supportare anche altre lingue. Se sei interessato a fornire aiuto, contatta l&apos;autore usando la form contenuta nella pagina sotto indicata..
        /// </summary>
        internal static string Form1_infoLabel {
            get {
                return ResourceManager.GetString("Form1_infoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installa.
        /// </summary>
        internal static string Form1_installGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_installGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installa.
        /// </summary>
        internal static string Form1_InstallPhase {
            get {
                return ResourceManager.GetString("Form1_InstallPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connessione.
        /// </summary>
        internal static string Form1_internetGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_internetGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Form1_InternetPhase {
            get {
                return ResourceManager.GetString("Form1_InternetPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad.
        /// </summary>
        internal static string Form1_introHeaderLabel {
            get {
                return ResourceManager.GetString("Form1_introHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto nel setup di DtPad!
        ///
        ///DtPad è un editor testuale, basato sul Framework .NET 4 (RICHIESTO, disponibile sul sito Microsoft) e distribuito sotto licenza Apache License, Version 2.0 (apache.org/licenses/LICENSE-2.0).
        ///
        ///Clicca sul bottone &quot;Avanti&quot; per procedere..
        /// </summary>
        internal static string Form1_introLabel {
            get {
                return ResourceManager.GetString("Form1_introLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzione.
        /// </summary>
        internal static string Form1_IntroPhase {
            get {
                return ResourceManager.GetString("Form1_IntroPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazione: DtPad utilizza le impostazioni di Internet Explorer per accedere a Internet.
        ///Se il tuo PC si trova dietro a un server proxy che richiede autenticazione, inserire qui di seguito utente e password..
        /// </summary>
        internal static string Form1_label1 {
            get {
                return ResourceManager.GetString("Form1_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string Form1_languageGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_languageGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la tua lingua:.
        /// </summary>
        internal static string Form1_languageLabel {
            get {
                return ResourceManager.GetString("Form1_languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string Form1_LanguagePhase {
            get {
                return ResourceManager.GetString("Form1_LanguagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diariotraduttore.com/contatti.
        /// </summary>
        internal static string Form1_linkContattiLabel {
            get {
                return ResourceManager.GetString("Form1_linkContattiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspetto.
        /// </summary>
        internal static string Form1_lookAndFeelGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_lookAndFeelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspetto.
        /// </summary>
        internal static string Form1_LookAndFeelPhase {
            get {
                return ResourceManager.GetString("Form1_LookAndFeelPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizza come icona in tray.
        /// </summary>
        internal static string Form1_minimizeOnTrayIconCheckBox {
            get {
                return ResourceManager.GetString("Form1_minimizeOnTrayIconCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanti &gt;.
        /// </summary>
        internal static string Form1_nextButton {
            get {
                return ResourceManager.GetString("Form1_nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installa.
        /// </summary>
        internal static string Form1_nextButtonInstall {
            get {
                return ResourceManager.GetString("Form1_nextButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia DtPad.
        /// </summary>
        internal static string Form1_nextButtonStart {
            get {
                return ResourceManager.GetString("Form1_nextButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Form1_passwordLabel {
            get {
                return ResourceManager.GetString("Form1_passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incolla.
        /// </summary>
        internal static string Form1_pasteToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_pasteToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spazio richiesto:.
        /// </summary>
        internal static string Form1_requiredSpaceLabel {
            get {
                return ResourceManager.GetString("Form1_requiredSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea associazione nella cartella &quot;Invia a&quot;.
        /// </summary>
        internal static string Form1_sendToCheckBox {
            get {
                return ResourceManager.GetString("Form1_sendToCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea collegamento in menu di Esplora risorse.
        /// </summary>
        internal static string Form1_shellCheckBox {
            get {
                return ResourceManager.GetString("Form1_shellCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea collegamento sul desktop e nel menu Start.
        /// </summary>
        internal static string Form1_shortcutsCheckBox {
            get {
                return ResourceManager.GetString("Form1_shortcutsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salta impostazioni (sarà possibile cambiarle in seguito tramite la finestra delle opzioni).
        /// </summary>
        internal static string Form1_skipSettingsCheckBox {
            get {
                return ResourceManager.GetString("Form1_skipSettingsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato:.
        /// </summary>
        internal static string Form1_statusLabel {
            get {
                return ResourceManager.GetString("Form1_statusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sempre in primo piano.
        /// </summary>
        internal static string Form1_stayOnTopCheckBox {
            get {
                return ResourceManager.GetString("Form1_stayOnTopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzione.
        /// </summary>
        internal static string Form1_stepLabel {
            get {
                return ResourceManager.GetString("Form1_stepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica.
        /// </summary>
        internal static string Form1_testProxyButton {
            get {
                return ResourceManager.GetString("Form1_testProxyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Setup.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non disponibile.
        /// </summary>
        internal static string Form1_Unavailable {
            get {
                return ResourceManager.GetString("Form1_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Form1_undoToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("Form1_undoToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente:.
        /// </summary>
        internal static string Form1_usernameLabel {
            get {
                return ResourceManager.GetString("Form1_usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finestra.
        /// </summary>
        internal static string Form1_windowGroupBox1 {
            get {
                return ResourceManager.GetString("Form1_windowGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finestra.
        /// </summary>
        internal static string Form1_WindowPhase {
            get {
                return ResourceManager.GetString("Form1_WindowPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows classico.
        /// </summary>
        internal static string Form1_windowsRadioButton {
            get {
                return ResourceManager.GetString("Form1_windowsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creazione associazione nella cartella &quot;Invia a&quot;....
        /// </summary>
        internal static string InstallManager_CreatingAssociation {
            get {
                return ResourceManager.GetString("InstallManager_CreatingAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creazione nuove cartelle....
        /// </summary>
        internal static string InstallManager_CreatingDir {
            get {
                return ResourceManager.GetString("InstallManager_CreatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creazione collegamenti nel menu Start....
        /// </summary>
        internal static string InstallManager_CreatingShortcut {
            get {
                return ResourceManager.GetString("InstallManager_CreatingShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cartella di destinazione contiene già DtPad. Sei sicuro di voler procedere?
        ///
        ///Tutti i file di configurazione verranno mantenuti, mentre il programma sarà sovrascritto..
        /// </summary>
        internal static string InstallManager_DestinationDirWithDtPad {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cartella di destinazione contiene già dei file. Sei sicuro di voler procedere?
        ///
        ///I file di DtPad verranno aggiunti alla cartella..
        /// </summary>
        internal static string InstallManager_DestinationDirWithFiles {
            get {
                return ResourceManager.GetString("InstallManager_DestinationDirWithFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca sul bottone &quot;Avvia DtPad&quot; per aprire l&apos;editor testuale..
        /// </summary>
        internal static string InstallManager_EndInfo {
            get {
                return ResourceManager.GetString("InstallManager_EndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante l&apos;installazione!.
        /// </summary>
        internal static string InstallManager_Error1 {
            get {
                return ResourceManager.GetString("InstallManager_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcuni file potrebbero essere rimasti nella cartella d&apos;installazione..
        /// </summary>
        internal static string InstallManager_Error2 {
            get {
                return ResourceManager.GetString("InstallManager_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccezione:.
        /// </summary>
        internal static string InstallManager_Exception {
            get {
                return ResourceManager.GetString("InstallManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrazione file....
        /// </summary>
        internal static string InstallManager_ExtractingFile {
            get {
                return ResourceManager.GetString("InstallManager_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installazione completata con successo!.
        /// </summary>
        internal static string InstallManager_InstallComplete {
            get {
                return ResourceManager.GetString("InstallManager_InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo di installazione interrotto dall&apos;utente..
        /// </summary>
        internal static string InstallManager_InstallInterrupted {
            get {
                return ResourceManager.GetString("InstallManager_InstallInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrazione DtPad nel menu di Esplora risorse....
        /// </summary>
        internal static string InstallManager_IntegratingShell {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante l&apos;integrazione nel menu di Esplora risorse!.
        /// </summary>
        internal static string InstallManager_IntegratingShellError {
            get {
                return ResourceManager.GetString("InstallManager_IntegratingShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia DtPad.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPad {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia DtPad Uninstaller.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUninstaller {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia DtPad Updater.
        /// </summary>
        internal static string InstallManager_LinkLaunchDtPadUpdater {
            get {
                return ResourceManager.GetString("InstallManager_LinkLaunchDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggi alcune informazioni su DtPad.
        /// </summary>
        internal static string InstallManager_LinkReadme {
            get {
                return ResourceManager.GetString("InstallManager_LinkReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sito web.
        /// </summary>
        internal static string InstallManager_LinkWebsite {
            get {
                return ResourceManager.GetString("InstallManager_LinkWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparazione installazione....
        /// </summary>
        internal static string InstallManager_PreparingInstall {
            get {
                return ResourceManager.GetString("InstallManager_PreparingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri con DtPad.
        /// </summary>
        internal static string InstallManager_ShellString {
            get {
                return ResourceManager.GetString("InstallManager_ShellString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non disponibile.
        /// </summary>
        internal static string InstallManager_Unavailable {
            get {
                return ResourceManager.GetString("InstallManager_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento impostazioni....
        /// </summary>
        internal static string InstallManager_UpdatingSetting {
            get {
                return ResourceManager.GetString("InstallManager_UpdatingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout della connessione!
        ///Il test ha richiesto più di {0} secondi per essere completata..
        /// </summary>
        internal static string OptionManager_ConnectionTimeout {
            get {
                return ResourceManager.GetString("OptionManager_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string WarningYNC_cancelButton {
            get {
                return ResourceManager.GetString("WarningYNC_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string WarningYNC_noButton {
            get {
                return ResourceManager.GetString("WarningYNC_noButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        internal static string WarningYNC_Title {
            get {
                return ResourceManager.GetString("WarningYNC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sì.
        /// </summary>
        internal static string WarningYNC_yesButton {
            get {
                return ResourceManager.GetString("WarningYNC_yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;esecuzione dell&apos;operazione in corso è stata interrotta!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;esecuzione del programma è stata interrotta!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
