//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUpdater.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUpdater.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy error message to clipboard.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form1_Close {
            get {
                return ResourceManager.GetString("Form1_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DtPad Updater!
        ///
        ///Click over &quot;Start Update&quot; botton to begin the update process. Any existing setting will be mantained.
        ///
        ///In case of errors, DtPad Updater will restore actual version files and it could be possible to repeat the process.
        ///
        ///If a problem persist, or DtPad seems to be broken, download the latest version from the link below..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DtPad Updater!
        ///
        ///Click on &quot;Start Update&quot; botton to begin the update process. Any existing setting will be mantained.
        ///
        ///In case of errors, DtPad Updater will restore the previous version of the file so you can re-launch the process.
        ///
        ///If a problem persist, or DtPad seems to be faulty, contact the author..
        /// </summary>
        internal static string Form1_descriptionLabel_FE {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start DtPad.
        /// </summary>
        internal static string Form1_Start {
            get {
                return ResourceManager.GetString("Form1_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Form1_startButton {
            get {
                return ResourceManager.GetString("Form1_startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Update.
        /// </summary>
        internal static string Form1_StartUpdate {
            get {
                return ResourceManager.GetString("Form1_StartUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string Form1_Updating {
            get {
                return ResourceManager.GetString("Form1_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This update contains:.
        /// </summary>
        internal static string Form1_whatIsInsideLabel {
            get {
                return ResourceManager.GetString("Form1_whatIsInsideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for &quot;{0}&quot; parameter not found..
        /// </summary>
        internal static string PasswordUtil_NoValue {
            get {
                return ResourceManager.GetString("PasswordUtil_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close any instance of DtHelp before to start the update process..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close any instance of DtPad before to start the update process..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close any instance of DtPad Uninstaller before to start the update process..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an opened instance of DtPad Updater..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backuping old version files....
        /// </summary>
        internal static string UpdateManager_Backup {
            get {
                return ResourceManager.GetString("UpdateManager_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting configuration key &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting temporary files....
        /// </summary>
        internal static string UpdateManager_DeleteTemp {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting update files....
        /// </summary>
        internal static string UpdateManager_DeleteUpd {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during update operation!.
        /// </summary>
        internal static string UpdateManager_Error {
            get {
                return ResourceManager.GetString("UpdateManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during DtPad Updater version check!.
        /// </summary>
        internal static string UpdateManager_ErrorCheckVersion {
            get {
                return ResourceManager.GetString("UpdateManager_ErrorCheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string UpdateManager_Exception {
            get {
                return ResourceManager.GetString("UpdateManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File in use.
        /// </summary>
        internal static string UpdateManager_FileInUse {
            get {
                return ResourceManager.GetString("UpdateManager_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding folder &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_DIR {
            get {
                return ResourceManager.GetString("UpdateManager_INS_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_INS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding configuration key &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_INS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Start DtPad&quot; button to open the new version..
        /// </summary>
        internal static string UpdateManager_Launch {
            get {
                return ResourceManager.GetString("UpdateManager_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available for your version of DtPad!.
        /// </summary>
        internal static string UpdateManager_NoInfo {
            get {
                return ResourceManager.GetString("UpdateManager_NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current DtPad Updater version is outdated.
        ///
        ///Start the update process from DtPad &quot;Help -&gt; Check for New Version...&quot; menu..
        /// </summary>
        internal static string UpdateManager_OldVersion {
            get {
                return ResourceManager.GetString("UpdateManager_OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using a proxy, try to set it on DtPad options window. If the problem persist manually download the last version from {0}!.
        /// </summary>
        internal static string UpdateManager_Proxy {
            get {
                return ResourceManager.GetString("UpdateManager_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading new version information....
        /// </summary>
        internal static string UpdateManager_Read {
            get {
                return ResourceManager.GetString("UpdateManager_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming file &quot;{0}&quot; in &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_REN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming configuration key &quot;{0}&quot; as &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_REN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your DtPad version is no longer supported! Download last version from DtPad website..
        /// </summary>
        internal static string UpdateManager_SHW_MSG_NoLongerUpdate {
            get {
                return ResourceManager.GetString("UpdateManager_SHW_MSG_NoLongerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad successfully updated!.
        /// </summary>
        internal static string UpdateManager_Success {
            get {
                return ResourceManager.GetString("UpdateManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating configuration key &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing version update....
        /// </summary>
        internal static string UpdateManager_Update {
            get {
                return ResourceManager.GetString("UpdateManager_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution interrupted!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal exception occured:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program execution interrupted!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
