//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUpdater.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUpdater.Languages.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar mensaje de error al portapapeles.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Form1_Close {
            get {
                return ResourceManager.GetString("Form1_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a DtPad Updater!
        ///
        ///Haga click sobre &quot;Iniciar actualización&quot; botton para iniciar el proceso de actualización. Cualquier configuración existente será mantenida.
        ///
        ///En caso de errores, DtPad Updater restaurará los archivos reales versión y podría ser posible repetir el proceso.
        ///
        ///Si el problema persiste, o DtPad parece estar roto, descargue la última versión desde el siguiente vínculo..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a DtPad Updater!
        ///
        ///Haga click sobre &quot;Iniciar actualización&quot; botton para iniciar el proceso de actualización. Cualquier configuración existente será mantenida.
        ///
        ///En caso de errores, DtPad Updater restaurará los archivos reales versión y podría ser posible repetir el proceso.
        ///
        ///Si el problema persiste, o DtPad parece estar roto, póngase en contacto con el autor..
        /// </summary>
        internal static string Form1_descriptionLabel_FE {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todo.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar DtPad.
        /// </summary>
        internal static string Form1_Start {
            get {
                return ResourceManager.GetString("Form1_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar actualización.
        /// </summary>
        internal static string Form1_startButton {
            get {
                return ResourceManager.GetString("Form1_startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando....
        /// </summary>
        internal static string Form1_Updating {
            get {
                return ResourceManager.GetString("Form1_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor para &quot;{0}&quot; parámetro no fue encontrada..
        /// </summary>
        internal static string PasswordUtil_NoValue {
            get {
                return ResourceManager.GetString("PasswordUtil_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre cualquier instancia de DtHelp antes de iniciar el proceso de actualización..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre cualquier instancia de DtPad antes de iniciar el proceso de actualización..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre cualquier instancia de DtPad Uninstaller antes de iniciar el proceso de actualización..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una instancia abierta de DtPad Updater..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haciendo copia de seguridad de archivos....
        /// </summary>
        internal static string UpdateManager_Backup {
            get {
                return ResourceManager.GetString("UpdateManager_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando archivo &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando clave de configuración &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando archivos temporales....
        /// </summary>
        internal static string UpdateManager_DeleteTemp {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando archivos de actualización....
        /// </summary>
        internal static string UpdateManager_DeleteUpd {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error durante el proceso de actualización!.
        /// </summary>
        internal static string UpdateManager_Error {
            get {
                return ResourceManager.GetString("UpdateManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la comprobación de la versión de DtPad Updater!.
        /// </summary>
        internal static string UpdateManager_ErrorCheckVersion {
            get {
                return ResourceManager.GetString("UpdateManager_ErrorCheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción:.
        /// </summary>
        internal static string UpdateManager_Exception {
            get {
                return ResourceManager.GetString("UpdateManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo en uso.
        /// </summary>
        internal static string UpdateManager_FileInUse {
            get {
                return ResourceManager.GetString("UpdateManager_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregando carpeta &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_DIR {
            get {
                return ResourceManager.GetString("UpdateManager_INS_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregando archivo &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_INS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregando clave de configuración &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_INS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic en &quot;Iniciar DtPad&quot; para abrir la nueva versión..
        /// </summary>
        internal static string UpdateManager_Launch {
            get {
                return ResourceManager.GetString("UpdateManager_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay información de actualización para su versión DtPad!.
        /// </summary>
        internal static string UpdateManager_NoInfo {
            get {
                return ResourceManager.GetString("UpdateManager_NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual versión de DtPad Updater no está actualizado.
        ///
        ///Inicie el proceso de actualización desde el menú DtPad &quot;Ayuda -&gt; Compruebe si hay nueva versión...&quot;..
        /// </summary>
        internal static string UpdateManager_OldVersion {
            get {
                return ResourceManager.GetString("UpdateManager_OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si usted está usando un proxy, intenta ponerlo en DtPad ventana de opciones. Si el problema persiste descargar manualmente la última versión de {0}!.
        /// </summary>
        internal static string UpdateManager_Proxy {
            get {
                return ResourceManager.GetString("UpdateManager_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leyendo la información de la nueva versión....
        /// </summary>
        internal static string UpdateManager_Read {
            get {
                return ResourceManager.GetString("UpdateManager_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiando nombre de archivo &quot;{0}&quot; en &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_REN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiando clave de configuración &quot;{0}&quot; en &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_REN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su versión de DtPad ya no es compatible! Descargue la última versión de la página web de DtPad..
        /// </summary>
        internal static string UpdateManager_SHW_MSG_NoLongerUpdate {
            get {
                return ResourceManager.GetString("UpdateManager_SHW_MSG_NoLongerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad actualizado con éxito!.
        /// </summary>
        internal static string UpdateManager_Success {
            get {
                return ResourceManager.GetString("UpdateManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando archivo &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando clave de configuración &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando la versión....
        /// </summary>
        internal static string UpdateManager_Update {
            get {
                return ResourceManager.GetString("UpdateManager_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecución de comandos interrumpida!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecución del programa interrumpido!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
