//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUpdater.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUpdater.Languages.it", typeof(it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia il messaggio di errore negli appunti.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        internal static string Form1_Close {
            get {
                return ResourceManager.GetString("Form1_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto in DtPad Updater!
        ///
        ///Clicca su &quot;Aggiorna&quot; per avviare l&apos;aggiornamento. Le impostazioni attualmente salvate saranno mantenute.
        ///
        ///In caso di errori, DtPad Updater ripristinerà i file della versione precedente di modo da poter rilanciare il processo.
        ///
        ///Se un problema persiste, o DtPad dovesse sembrare malfunzionante, si consiglia di scaricare l&apos;ultima versione dal link sottostante..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto in DtPad Updater!
        ///
        ///Clicca su &quot;Aggiorna&quot; per avviare l&apos;aggiornamento. Le impostazioni attualmente salvate saranno mantenute.
        ///
        ///In caso di errori, DtPad Updater ripristinerà i file della versione precedente di modo da poter rilanciare il processo.
        ///
        ///Se un problema persiste, o DtPad dovesse sembrare malfunzionante, si consiglia di contattare l&apos;autore..
        /// </summary>
        internal static string Form1_descriptionLabel_FE {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia DtPad.
        /// </summary>
        internal static string Form1_Start {
            get {
                return ResourceManager.GetString("Form1_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna.
        /// </summary>
        internal static string Form1_startButton {
            get {
                return ResourceManager.GetString("Form1_startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In corso....
        /// </summary>
        internal static string Form1_Updating {
            get {
                return ResourceManager.GetString("Form1_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore per il parametro &quot;{0}&quot; non trovato..
        /// </summary>
        internal static string PasswordUtil_NoValue {
            get {
                return ResourceManager.GetString("PasswordUtil_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi ogni finestra di DtHelp prima di avviare il processo di aggiornamento..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi ogni finestra di DtPad prima di avviare il processo di aggiornamento..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi ogni finestra di DtPad Uninstaller prima di avviare il processo di aggiornamento..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esiste già una finestra aperta di DtPad Updater..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup dei file precedenti....
        /// </summary>
        internal static string UpdateManager_Backup {
            get {
                return ResourceManager.GetString("UpdateManager_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione file &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione parametro di configurazione &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione file temporanei....
        /// </summary>
        internal static string UpdateManager_DeleteTemp {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione file aggiornamento....
        /// </summary>
        internal static string UpdateManager_DeleteUpd {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante l&apos;aggiornamento!.
        /// </summary>
        internal static string UpdateManager_Error {
            get {
                return ResourceManager.GetString("UpdateManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il controllo di versione di DtPadUpdater!.
        /// </summary>
        internal static string UpdateManager_ErrorCheckVersion {
            get {
                return ResourceManager.GetString("UpdateManager_ErrorCheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccezione:.
        /// </summary>
        internal static string UpdateManager_Exception {
            get {
                return ResourceManager.GetString("UpdateManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File in uso.
        /// </summary>
        internal static string UpdateManager_FileInUse {
            get {
                return ResourceManager.GetString("UpdateManager_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunta cartella &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_DIR {
            get {
                return ResourceManager.GetString("UpdateManager_INS_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunto file &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_INS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunto parametro di configurazione &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_INS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca sul bottone &quot;Avvia DtPad&quot; per aprire la nuova versione..
        /// </summary>
        internal static string UpdateManager_Launch {
            get {
                return ResourceManager.GetString("UpdateManager_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun aggiornamento disponibile per la versione presente di DtPad!.
        /// </summary>
        internal static string UpdateManager_NoInfo {
            get {
                return ResourceManager.GetString("UpdateManager_NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versione attuale di DtPadUpdater non è aggiornata.
        ///
        ///Avvia il processo di aggiornamento dal menu &quot;? -&gt; Controlla aggiornamenti...&quot; in DtPad..
        /// </summary>
        internal static string UpdateManager_OldVersion {
            get {
                return ResourceManager.GetString("UpdateManager_OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se usi un proxy, impostalo nella finestra delle opzioni di DtPad. Se il problema persiste scarica manualmente l&apos;ultima versione di DtPad da www.diariotraduttore.com!.
        /// </summary>
        internal static string UpdateManager_Proxy {
            get {
                return ResourceManager.GetString("UpdateManager_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettura informazioni nuova versione....
        /// </summary>
        internal static string UpdateManager_Read {
            get {
                return ResourceManager.GetString("UpdateManager_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinomina file &quot;{0}&quot; in &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_REN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rinomina parametro di configurazione &quot;{0}&quot; in &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_REN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tua versione di DtPad non è più supportata! Scarica l&apos;ultima dal sito di DtPad..
        /// </summary>
        internal static string UpdateManager_SHW_MSG_NoLongerUpdate {
            get {
                return ResourceManager.GetString("UpdateManager_SHW_MSG_NoLongerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad è stato aggiornato con successo!.
        /// </summary>
        internal static string UpdateManager_Success {
            get {
                return ResourceManager.GetString("UpdateManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento file &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento parametro di configurazione &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento in corso....
        /// </summary>
        internal static string UpdateManager_Update {
            get {
                return ResourceManager.GetString("UpdateManager_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;esecuzione dell&apos;operazione in corso è stata interrotta!.
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificata un&apos;eccezione grave:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;esecuzione del programma è stata interrotta!.
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
