//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtPadUpdater.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DtPadUpdater.Languages.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string AlertO_okButton {
            get {
                return ResourceManager.GetString("AlertO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение.
        /// </summary>
        internal static string AlertO_Title {
            get {
                return ResourceManager.GetString("AlertO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать сообщение об ошибке в буфер.
        /// </summary>
        internal static string ErrorO_copyErrorDescriptionPictureBoxToolTip {
            get {
                return ResourceManager.GetString("ErrorO_copyErrorDescriptionPictureBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string ErrorO_okButton {
            get {
                return ResourceManager.GetString("ErrorO_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorO_Title {
            get {
                return ResourceManager.GetString("ErrorO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Form1_cancelButton {
            get {
                return ResourceManager.GetString("Form1_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Form1_Close {
            get {
                return ResourceManager.GetString("Form1_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string Form1_copyToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_copyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас приветствует DtPad Updater!
        ///
        ///Чтобы приступить к обновлению, нажмите кнопку &quot;Запустить обновление&quot;. При этом все настройки DtPad сохранятся.
        ///
        ///В случае ошибок DtPad Updater восстановит файлы текущей версии, после чего процесс обновления можно будет повторить.
        ///
        ///Если проблема не исчезает или программа DtPad функционирует неправильно, загрузите последнюю версию по приведенной ниже ссылке..
        /// </summary>
        internal static string Form1_descriptionLabel {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас приветствует DtPad Updater!
        ///
        ///Чтобы приступить к обновлению, нажмите кнопку &quot;Запустить обновление&quot;. При этом все настройки DtPad сохранятся.
        ///
        ///В случае ошибок DtPad Updater восстановит предыдущие версии файлов, после чего процесс обновления можно будет повторить.
        ///
        ///Если проблема не исчезает или программа DtPad функционирует неправильно, свяжитесь с автором..
        /// </summary>
        internal static string Form1_descriptionLabel_FE {
            get {
                return ResourceManager.GetString("Form1_descriptionLabel_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При загрузке протокола изменений DtPad произошла ошибка..
        /// </summary>
        internal static string Form1_ErrorLoadingChangeLog {
            get {
                return ResourceManager.GetString("Form1_ErrorLoadingChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить все.
        /// </summary>
        internal static string Form1_selectAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("Form1_selectAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить DtPad.
        /// </summary>
        internal static string Form1_Start {
            get {
                return ResourceManager.GetString("Form1_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее &gt;.
        /// </summary>
        internal static string Form1_startButton {
            get {
                return ResourceManager.GetString("Form1_startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить обновление.
        /// </summary>
        internal static string Form1_StartUpdate {
            get {
                return ResourceManager.GetString("Form1_StartUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater.
        /// </summary>
        internal static string Form1_titleLabel {
            get {
                return ResourceManager.GetString("Form1_titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление....
        /// </summary>
        internal static string Form1_Updating {
            get {
                return ResourceManager.GetString("Form1_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этом обновлении:.
        /// </summary>
        internal static string Form1_whatIsInsideLabel {
            get {
                return ResourceManager.GetString("Form1_whatIsInsideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка протокола изменений...
        ///
        ///Дожидаться загрузки протокола изменений не обязательно.
        ///Просто нажмите кнопку &quot;Запустить обновление&quot;, когда пожелаете выполнить обновление..
        /// </summary>
        internal static string Form1_whatIsInsideTextBox {
            get {
                return ResourceManager.GetString("Form1_whatIsInsideTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение параметра &quot;{0}&quot; не найдено..
        /// </summary>
        internal static string PasswordUtil_NoValue {
            get {
                return ResourceManager.GetString("PasswordUtil_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте все работающие экземпляры DtHelp, прежде чем приступать к обновлению..
        /// </summary>
        internal static string Program_InstanceDtHelp {
            get {
                return ResourceManager.GetString("Program_InstanceDtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте все работающие экземпляры DtPad, прежде чем приступать к обновлению..
        /// </summary>
        internal static string Program_InstanceDtPad {
            get {
                return ResourceManager.GetString("Program_InstanceDtPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте все работающие экземпляры DtPad Uninstaller, прежде чем приступать к обновлению..
        /// </summary>
        internal static string Program_InstanceDtPadUninstaller {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtPad Updater уже открыт..
        /// </summary>
        internal static string Program_InstanceDtPadUpdater {
            get {
                return ResourceManager.GetString("Program_InstanceDtPadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание резервных копий файлов старой версии....
        /// </summary>
        internal static string UpdateManager_Backup {
            get {
                return ResourceManager.GetString("UpdateManager_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление файла &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление ключа конфигурации &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_DEL_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_DEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление временных файлов....
        /// </summary>
        internal static string UpdateManager_DeleteTemp {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление файлов обновления....
        /// </summary>
        internal static string UpdateManager_DeleteUpd {
            get {
                return ResourceManager.GetString("UpdateManager_DeleteUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обновлении произошла ошибка..
        /// </summary>
        internal static string UpdateManager_Error {
            get {
                return ResourceManager.GetString("UpdateManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при проверке версии DtPad Updater..
        /// </summary>
        internal static string UpdateManager_ErrorCheckVersion {
            get {
                return ResourceManager.GetString("UpdateManager_ErrorCheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исключение:.
        /// </summary>
        internal static string UpdateManager_Exception {
            get {
                return ResourceManager.GetString("UpdateManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл занят.
        /// </summary>
        internal static string UpdateManager_FileInUse {
            get {
                return ResourceManager.GetString("UpdateManager_FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление папки &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_DIR {
            get {
                return ResourceManager.GetString("UpdateManager_INS_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление файла &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_INS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление ключа конфигурации &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_INS_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_INS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите кнопку &quot;Запустить DtPad&quot;, чтобы открыть новую версию редактора..
        /// </summary>
        internal static string UpdateManager_Launch {
            get {
                return ResourceManager.GetString("UpdateManager_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для вашей версии DtPad нет обновлений..
        /// </summary>
        internal static string UpdateManager_NoInfo {
            get {
                return ResourceManager.GetString("UpdateManager_NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая версия DtPad Updater устарела.
        ///
        ///Запустите обновление из DtPad, выбрав в меню команду &quot;Справка -&gt; Проверить наличие новой версии...&quot;..
        /// </summary>
        internal static string UpdateManager_OldVersion {
            get {
                return ResourceManager.GetString("UpdateManager_OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы используете прокси-сервер, попробуйте указать его в окне параметров DtPad. Если проблема не исчезает, вручную загрузите последнюю версию с веб-сайта {0}..
        /// </summary>
        internal static string UpdateManager_Proxy {
            get {
                return ResourceManager.GetString("UpdateManager_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение сведений о новой версии....
        /// </summary>
        internal static string UpdateManager_Read {
            get {
                return ResourceManager.GetString("UpdateManager_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименование файла &quot;{0}&quot; в &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_REN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименование ключа конфигурации &quot;{0}&quot; в &quot;{1}&quot;....
        /// </summary>
        internal static string UpdateManager_REN_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_REN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша версия DtPad более не поддерживается. Загрузите последнюю версию с веб-сайта DtPad..
        /// </summary>
        internal static string UpdateManager_SHW_MSG_NoLongerUpdate {
            get {
                return ResourceManager.GetString("UpdateManager_SHW_MSG_NoLongerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа DtPad обновлена..
        /// </summary>
        internal static string UpdateManager_Success {
            get {
                return ResourceManager.GetString("UpdateManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление файла &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_FILE {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление ключа конфигурации &quot;{0}&quot;....
        /// </summary>
        internal static string UpdateManager_UPD_KEY {
            get {
                return ResourceManager.GetString("UpdateManager_UPD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление версии....
        /// </summary>
        internal static string UpdateManager_Update {
            get {
                return ResourceManager.GetString("UpdateManager_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнение команды прервано..
        /// </summary>
        internal static string WindowManager_CommandExecution {
            get {
                return ResourceManager.GetString("WindowManager_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникло исключение:.
        /// </summary>
        internal static string WindowManager_Exception {
            get {
                return ResourceManager.GetString("WindowManager_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникло неустранимое исключение:.
        /// </summary>
        internal static string WindowManager_FatalException {
            get {
                return ResourceManager.GetString("WindowManager_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение программы прервано..
        /// </summary>
        internal static string WindowManager_ProgramExecution {
            get {
                return ResourceManager.GetString("WindowManager_ProgramExecution", resourceCulture);
            }
        }
    }
}
